///////////////////////////////////////////////////////////////////////////////
// # License
// <b>Copyright 2022  Silicon Laboratories Inc. www.silabs.com</b>
///////////////////////////////////////////////////////////////////////////////
// The licensor of this software is Silicon Laboratories Inc. Your use of this
// software is governed by the terms of Silicon Labs Master Software License
// Agreement (MSLA) available at
// www.silabs.com/about-us/legal/master-software-license-agreement. This
// software is distributed to you in Source Code format and is governed by the
// sections of the MSLA applicable to Source Code.
//
///////////////////////////////////////////////////////////////////////////////

/// Include the source code of the binding file generated by cargo-bindgen. As
/// argument pass the filename that is given for the binding_generator
/// configuration.
///
#[macro_export]
macro_rules! include_binding {
    ($name:expr, $mod_name: ident) => {
        mod $mod_name {
            #![allow(
                missing_docs,
                dead_code,
                non_snake_case,
                non_camel_case_types,
                non_upper_case_globals
            )]
            use super::*;
            include!($name);
        }
    };
}
