@startuml SDKOverview

skinparam roundCorner 15

top to bottom direction

cloud "IoT Services" as IOTService {
    rectangle "Developer GUI" as DEVGUI #FEFECE
    rectangle "UPTICap" as UPTICAP #FEFECE
    rectangle "UPTIWriter" as UPTIWRITER #FEFECE
    rectangle "Matter Bridge" as UMB #FEFECE

    DEVGUI -[hidden]r->UPTICAP
    UPTICAP -[hidden]r->UPTIWRITER 
    UPTIWRITER -[hidden]r->UMB
}

rectangle "IoT Gateway" {

    package "Unify Framework services" as services {
        rectangle "NAL" as NAL #FEFECE
        rectangle "UPVL" as UPVL #FEFECE
        rectangle "Image provider" as IMP #FEFECE
        rectangle "GMS" as GMS #FEFECE
    }

    rectangle "MQTT Broker" as Broker {
        rectangle "Unify Controller Language (UCL)" as ABLayer #FEFECE
    }

    ABLayer <-> services

    GMS -[hidden]r-> IMP
    IMP -[hidden]r-> NAL
    NAL -[hidden]d-> GMS

    package "Unify Framework protocol controllers" as PCS {
        rectangle "Z-Wave - ZPC" as ZPC #FEFECE
        rectangle "Proprietary PC" as ProprietaryPC #FEFECE
    }

    package "Emulators" as Emulators {
        rectangle "Emulated End Device" as EED #FEFECE
    }
}

ZPC -[hidden]r-> ProprietaryPC
EED -[hidden]r-> PCS

' Relation between EED and MQTT abstraction layer
ABLayer <-d-> EED

' Relation between Protocol controllers and MQTT abstraction layer
ABLayer <-d-> PCS

' IoT Services relation to the rest
IOTService <-d-> ABLayer


@enduml