#!/bin/sh
systemctl --system daemon-reload
systemctl enable uic-dev-gui-api.service
systemctl enable uic-dev-gui-server.service
systemctl start uic-dev-gui-api.service
systemctl start uic-dev-gui-server.service
