@startuml ota_internal.svg
title OTA download from image provider

participant "OTA cache" as OTAC
participant "OTA API" as API
participant "Protocol controller" as PC
participant "Image provider" as IP

PC -> API: subscribe_unid(unid, uiid)

alt If no unids listening to uiid
API -> IP: Subscribe: ucl/OTA/info/uiid/all
end
API -> IP: Subscribe: ucl/OTA/info/uiid/unid
API -> OTAC: unid listening to uiid
alt #LightBlue specific unid available
== image availability ==
IP -> API: Publish: ucl/OTA/info/uiid/unid
API -> OTAC: Cache image meta info for uiid/unid
API -> PC: image_available_callback(meta_info)
== image download ==
PC -> API: get_by_unid(unid, uiid, image_ready_cb)
alt #LightBlue image not cached
API -> IP: Subscribe: ucl/OTA/data/uiid/unid
API -> IP: Publish: ucl/OTA/info/uiid/unid/get
alt #LightBlue image received
IP -> API: Publish: image file data message
API -> OTAC: Cache image file
API -> PC: image_ready_cb(OK, filepath)
else no image received
API -> PC: image_ready_cb(ERROR, "")
end
API -> IP: Unsubscribe: ucl/OTA/data/uiid/unid
else #LightBlue image cached
API -> OTAC: get image filepath from cache
OTAC -> API: image filepath
API -> PC: image_ready_cb(OK, filepath)
end

else #LightGreen no specific unid available
== image availability ==
IP -> API: Publish: ucl/OTA/info/uiid/all
API -> OTAC: Cache image meta info for uiid/all
API -> OTAC: get_unids_listening_to_uiid()
OTAC -> API: list of unids listening to the uiid
loop #LightGreen for all unids listening to uiid
API -> PC: image_available_callback(meta_info)
== image download ==
PC -> API: get_by_unid(unid, uiid, image_ready_cb)
alt #LightGreen image not cached
API -> IP: Subscribe: ucl/OTA/data/uiid/all
API -> IP: Publish: ucl/OTA/info/uiid/all/get
alt #LightGreen image received
IP -> API: image file data message
API -> OTAC: cache image file
API -> PC: image_ready_cb(OK, filepath)
else #LightGreen no image received
API -> PC: image_ready_cb(ERROR, "")
end
API -> IP: Unsubscribe: ucl/OTA/data/uiid/all
else #LightGreen image cached
API -> OTAC: get image filepath from cache
OTAC -> API: image filepath
API -> PC: image_ready_cb(OK, filepath)
end
end
end
PC -> API: unsubscribe_unid(unid, uiid)
API -> OTAC: remove unid listening to uiid
API -> IP: Unsubscribe: ucl/OTA/info/uiid/unid
alt If no more unids listening to uiid
API -> IP: Unsubscribe: ucl/OTA/info/uiid/all
end
@enduml
@startuml inline_umlgraph_1.svg
participant "MQTT" as mqtt
participant "DotDot MQTT" as dotdot
participant "OnOff Mapper" as onoff

note over mqtt, onoff
In this example only OnOff mappers are shown.
But there should exist mappers for all supported ZCL Clusters.
In addition only a selection of the supported commands for each of these mappers are shown here.
end note
=== Initialization ==
onoff    -> dotdot: uic_mqtt_dotdot_on_off_on_callback_set(on_cb)
onoff    -> dotdot: uic_mqtt_dotdot_on_off_off_callback_set(off_cb)
onoff    -> dotdot: uic_mqtt_dotdot_set_on_off_write_attributes_callback(on_att_cb)

note over dotdot: uic_mqtt_dotdot_init() is called

dotdot -> mqtt:     uic_mqtt_subscribe("ucl/by-unid/+/+/OnOff/Commands/On", ...);
dotdot -> mqtt:     uic_mqtt_subscribe("ucl/by-unid/+/+/OnOff/Commands/Off", ...);
dotdot -> mqtt:     uic_mqtt_subscribe("ucl/by-unid/+/+/OnOff/Commands/WriteAttributes", ...)
... ...
note over onoff: An end device is added
onoff -> dotdot:    uic_mqtt_dotdot_publish_supported_commands(unid, endpoint)
dotdot -> onoff:    on_cb(unid, endpoint, UIC_MQTT_DOTDOT_CALLBACK_TYPE_SUPPORT_CHECK)
dotdot -> onoff:    off_cb(unid, endpoint, UIC_MQTT_DOTDOT_CALLBACK_TYPE_SUPPORT_CHECK)

note over dotdot, onoff
When uic_mqtt_dotdot_publish_supported_commands is called,
DotDot MQTT calls all registered OnOff command callback functions
with UIC_MQTT_DOTDOT_CALLBACK_TYPE_SUPPORT_CHECK.
When the Command is supported by the unid/endpoint
SL_STATUS_OK shall be returned, otherwise SL_STATUS_NOT_AVAILABLE.

In this example both callbacks returns SL_STATUS_OK
end note

dotdot -> mqtt:     uic_mqtt_publish("ucl/by-unid/<unid>/ep<x>/OnOff/SupportedCommands", "[\"On\", \"Off\"]")
... ...
note over mqtt: IoT Service has published an OnOff/Commands/Off
mqtt -> dotdot:     uic_mqtt_dotdot_on_on_off_off(topic, message)
dotdot -> onoff:    on_cb(unid, endpoint, UIC_MQTT_DOTDOT_CALLBACK_TYPE_NORMAL)
@enduml
@startuml ota_image_listener_component.svg
title OTA Image Listener component
legend top
<font color=#0039FB>MQTT Subscription</font>
<font color=#2b3618>MQTT Unsubscribe</font>
<font color=#00003C>Retained MQTT Publication</font>
<font color=#6C2A0D>Unretained MQTT Publication</font>
endlegend

participant "Protocol Controller" as PC
participant "OTA" as IL
participant "MQTT Broker" as MQTT

note over IL
- 'image_available' callback with data containing meta data the newly available image.
- 'image_base_path' path used to download the images to.
- 'cache_size' defines the max amount of images to be cached by the ota component.
- 'timeout' the time before a get function returns with result TIMEOUT
end note
PC-> IL: init(image_available, image_base_path, cache_size, timeout)
note over IL: we have 2 ways to subscribe for images; 1. via uiid 2. via unid's (uiid, unid)
PC->IL:subscribe_uiid(uiid)
activate IL
IL->MQTT:<font color=#0039FB>ucl/OTA/info/<UIID>/all</font>
IL-->PC
deactivate IL
== node discovery ==
loop for n nodes in the network
note over IL
The PC is responsible to obtian nodes and their corresponding fwk versioning info.
Secondly, it needs to tell us when a node is not part of a network anymore.
end note
PC->IL:subscribe_unid(unid, uiid)
activate IL
IL->MQTT:<font color=#0039FB>ucl/OTA/info/<UIID>/<UNID></font>
IL-->PC
deactivate IL
end
...
...
note over MQTT: new image coming in!
MQTT->IL: <font color=#00003C>ucl/OTA/info/<UIID>/all/+</font>
activate IL
IL->PC:image_available(uiid, unid, new_version, apply_after)
deactivate IL
note over PC: protocol controller decides to get the image
PC->IL: get(uiid, image_ready_cb)
activate IL
IL->MQTT:<font color=#0039FB>ucl/OTA/data/<UIID></font>
IL->MQTT:<font color=#6C2A0D>ucl/OTA/data/<UIID>/get</font>
MQTT->IL:<font color=#6C2A0D>ucl/OTA/data/<UIID></font>
IL->MQTT:<font color=#2b3618> ucl/OTA/data/<UIID></font>
IL->PC: image_ready_cb(image_meta)
deactivate IL

...
note over PC: protocol controller sends updates to the image_listener
PC->IL: update_*status*(uiid, unid, endpoint, *status*)
activate IL
IL-> MQTT: <font color=#00003C>ucl/by-unid/<UNID>/OTA/<UIID>/+
IL-->PC
deactivate IL
...

PC->IL:unregister_unid(unid)
activate IL
IL-> MQTT: <font color=#00003C>ucl/by-unid/<UNID>/OTA/<UIID>/+
deactivate IL
PC->IL: unregister(uiid)
PC->IL: clear_cache()
@enduml
@startuml inline_umlgraph_3.svg
participant MQTT
participant SmartStartManagement as SSM
participant ProtocolControllerSmartStartManagement as PCSSM

note over SSM: Init
SSM         -> MQTT : Subscribe to <i>ucl/SmartStart/List</i>
MQTT        -> SSM  : onMqttPublish(<i>ucl/SmartStart/List</i>)
note over SSM       : Update smartstart_cache
SSM         -> PCSSM: on_smartstart_state_changed()
note over PCSSM : Enable/Disable Inclusion of SmartStart Devices
... Time goes by ...
group Node Added from ProtocolController
  note over PCSSM   : Node added with SmartStart
  PCSSM     -> SSM  : get_cache_entry(unid)
  note over PCSSM   : If node is found in cache continue to add the node
  PCSSM     -> SSM  : notify_node_added(key, unid)
  SSM       -> MQTT : Publish(<i>ucl/SmartStart/List/Update</i>, data)\ndata contains the updated    SmartStart entry,\nthat has been added
  MQTT        -> SSM  : onMqttPublish(<i>ucl/SmartStart/List</i>)
  note over SSM       : Update smartstart_cache
end
group Node Removed from ProtocolController
  note over PCSSM   : Node Removed from Network
  PCSSM     -> SSM  : notify_node_removed(unid)
  SSM       -> MQTT : Publish(<i>ucl/SmartStart/List/Update</i>, data)\ndata contains the updated    SmartStart entry,\nthat has been removed
  MQTT        -> SSM  : onMqttPublish(<i>ucl/SmartStart/List</i>)
  note over SSM       : Update smartstart_cache
end

group Node Added in SmartStartList
  MQTT      -> SSM  : onMqttPublish(<i>ucl/SmartStart/List</i>)
  note over SSM     : Update smartstart_cache
  SSM       -> PCSSM: on_smartstart_state_changed()
end
group Node Removed from ProtocolController
  MQTT      -> SSM  : onMqttPublish(<i>ucl/SmartStart/List</i>)
  note over SSM     : Update smartstart_cache
  SSM       -> PCSSM: on_smartstart_state_changed()
end
@enduml
@startuml inline_umlgraph_5.svg
  box "MQTT Broker" #LightYellow
  participant MQTT
  end box

  box "ZPC" #LightBlue
  participant StateTopic
  participant AttributeStore
  end box
  note over StateTopic,AttributeStore: Init
  StateTopic          -> AttributeStore       : attribute_store_register_callback_by_type(att_store_node_cb, ATTRIBUTE_NODE_ID)
  StateTopic          -> AttributeStore       : attribute_store_register_callback_by_type_and_state(att_store_network_status_cb, DOTDOT_ATTRIBUTE_ID_STATE_NETWORK_STATUS, REPORTED_ATTRIBUTE)
  ... ...
  note over StateTopic,AttributeStore: NETWORK_STATUS updated (ZCL_NODE_STATE_NETWORK_STATUS_ONLINE_FUNCTIONAL)
  AttributeStore      -> StateTopic           : att_store_network_status_cb(NETWORK_STATUS, ATTRIBUTE_UPDATED)
  StateTopic          -> MQTT                 : <i>ucl/by-unid/<new-node>/State</i>\n{"NetworkState": "Included", ...}
  ... ...
  note over StateTopic,AttributeStore: Remove Node
  AttributeStore      -> StateTopic           : att_store_node_cb(node_id, ATTRIBUTE_DELETED)
  StateTopic          -> MQTT                 : delete <i>ucl/by-unid/<new-node></i>
@enduml
@startuml inline_umlgraph_7.svg
title Relationships - Class Diagram

title Mapping engine

class ast::MapperEngine
class ast::UAMGrammer
class ast::eval
class ast::dep_eval
class attribute_store

ast::MapperEngine <|-down- ast::UAMGrammer : AST
ast::MapperEngine <|-down- ast::eval : optional value
ast::MapperEngine <|-down- ast::dep_eval : dependencies
ast::MapperEngine <|-up-   attribute_store:  on_attribute_updated()
@enduml
