import os
from posixpath import dirname
import shutil
import subprocess

# UAM lexer, to be moved in a separate file if possible.
from pygments.lexer import RegexLexer
from pygments.token import *

class uam_lexer(RegexLexer):
    name = 'UAM'
    aliases = ['uam']
    filenames = ['*.uam']

    tokens = {
        'root': [
            (r'//.*?$', Comment.Singleline),
            (r"scope|def", Name.Builtin),
            (r"if", Name.Builtin),
            (r"[rde]'[a-zA-Z0-9_]+(\[[a-zA-Z0-9_]+\])*(\.[a-zA-Z0-9_]+(\[[a-zA-Z0-9_]+\])*)*", Name.Variable),
            (r"[a-zA-Z0-9_]+", Name.Constant),
            (r'0x[0-9A-Fa-f]+', Token.Literal),
            (r'[0-9]+.[0-9]+f', Token.Literal),
            (r'[0-9]+', Token.Literal),
            (r"/|<|>|&|or|%|-|==", Operator.Word),
            (r"\*\*?", Operator.Word),
            (r"=", Operator),
            (r"\+", Operator.Word),
            (r"\|", Operator.Word),
            (r"undefined", Name.Variable.Magic),
            (r'\s+', Text),
            (r'.', Text),
        ]
    }



# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Unify"
copyright = "Copyright © 2022 Silicon Laboratories. All rights reserved."
author = "Silicon Labs"
language = "en"

root_doc = "doc/introduction"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration
html_additional_pages = {'index': 'index.html'}

extensions = [
    "breathe",
    "myst_parser",
    "sphinxcontrib.plantuml",
    "sphinx.ext.githubpages",
]

templates_path = ["_templates"]
exclude_patterns = ["_build",
                    "Thumbs.db",
                    ".DS_Store",
                    "**internal.md", "**/libs/cmock",
                    "components/testframework",
                    "**zwave_command_classes/README.md",
                    "**vscode-extension**",
                    "**dmt_match_generator**",
                    "**zw-libs2**",
                    "**uic-resources**",
                    "**dotdot-xml**",
                    "build**",
                    "LICENSE.md",
                    "README.md",
                    "**node_modules**",
                    "**uic_attribute_mapper/src/README.md",
                    "scripts/ci",
                    "**release_notes.md",
                    "externals",
                    "**build_**",
                    "unify-spec",
                    "scripts/ci",
                    "**applications/uhab**"]

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# enable all markdown features of the myst parser
myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

# setup plantuml plugin
plantuml = "java -jar " + os.environ["PLANTUML_JAR_PATH"]

# Sphinx doesn't support inclusion of documents outside of this own
# root folder. therefore setup and delete symlinks in order to access
# applications and components.
project_root = os.path.realpath(os.path.join(__file__, "..", ".."))

def setup_doxygen_project(project_name):
    doxygen = os.path.join(os.environ.get("UNIFY_BUILD"), project_name)
    if os.path.exists(doxygen):
        # For now we hyperlink to the html generated by doxygen
        html = os.path.join(doxygen, "html")
        if os.path.exists(html):
            dest = os.path.join(
                os.environ.get("UNIFY_BUILD"), 'sphinx', project_name)
            if os.path.exists(dest):
                shutil.rmtree(dest)
            shutil.copytree(html, dest)
    else:
        print("could not find " + doxygen)


if os.environ.get("UNIFY_BUILD") is not None:
    setup_doxygen_project("doxygen_uic")
    setup_doxygen_project("doxygen_zigpc")
    setup_doxygen_project("doxygen_zpc")
    setup_doxygen_project("reference_ucl_mqtt")

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_css_files = ["custom_styles.css"]
html_logo = "doxygen/assets/silicon-labs-logo.png"
html_title = "Unify Host SDK"
html_baseurl = "https://siliconlabs.github.io/UnifySDK"

releases_github_path = "SiliconLabs/UnifySDK"


# -- Options for LaTeX output ------------------------------------------------
latex_engine = "lualatex"

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # I just also aded "oneside", this string is just copied into the \documentclass[] content
    #
    "papersize": "a4paper,oneside",
    # The font size ('10pt', '11pt' or '12pt').
    #
    "pointsize": "10pt",
    # Latex figure (float) alignment
    #
    "figure_align": "H",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        root_doc,
        "unify_sdk_documentation.tex",
        "Unify Framework documentation",
        "Silicon Labs",
        "howto",
    ),
]

# Logo
latex_logo = "./doxygen/assets/silicon-labs-logo.png"


version = subprocess.check_output(["git", "describe"], text=True)


def setup(app):
    app.add_lexer('uam', uam_lexer)
