/******************************************************************************
 * # License
 * <b>Copyright 2021 Silicon Laboratories Inc. www.silabs.com</b>
 ******************************************************************************
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 *****************************************************************************/

/**
 * @file ucl_mqtt.h
 * @defgroup ucl_mqtt UCL MQTT
 * @ingroup components
 * @brief This file provides the shared documentation for the UCL MQTT component
 *
 * This component contains the various UCL MQTT interfaces, that doesn't exist
 * in DotDot, and thus isn't autogenerated as the DotDot cluster mappers.
 *
 * @{
 */

#ifndef UCL_MQTT_H
#define UCL_MQTT_H
#include "sl_status.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Setup fixture for the UCL MQTT component.
 *
 * Setup all modules in the UCL MQTT component.
 *
 * @return SL_STATUS_OK, always.
 */
sl_status_t ucl_mqtt_setup_fixt(void);

#ifdef __cplusplus
}
#endif

#endif  //UCL_MQTT_H
/** @} end ucl_mqtt */