[package]
name = "unify_build_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = "0.62.0"
once_cell= "1.9.0"
anyhow = "1.0.66"
regex= "1.5.6"
serde_yaml ="0.9"
serde = { version = "1.0.147", features = ["derive"] }
glob = "0.3.0"
