[package]
name = "unify_build_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
bindgen = "*"
anyhow = "*"
regex= "*"
serde_yaml ="*"
serde = { version = "*", features = ["derive"] }
glob = "*"