VERSION 0.6
FROM rust:1.60-slim-buster
WORKDIR /rust_application

build-all-platforms:
    BUILD +build-armv7
    BUILD +build-linux-x86
    BUILD +build-windows-x86
    BUILD +build-macos-x86

project-files:
    COPY unify_portable_cli unify_portable_cli
    COPY unify_portable_core unify_portable_core
    COPY Cargo.toml .

project-files-macos:
    FROM joseluisq/rust-linux-darwin-builder
    COPY unify_portable_cli unify_portable_cli
    COPY unify_portable_core unify_portable_core
    COPY Cargo.toml .

build-armv7:
    FROM +project-files
    RUN apt update && apt upgrade -y
    RUN apt install -y g++-arm-linux-gnueabihf libc6-dev-armhf-cross
    RUN rustup target add armv7-unknown-linux-gnueabihf
    RUN rustup toolchain install stable-armv7-unknown-linux-gnueabihf
    ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
    ENV CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc
    ENV CXX_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-g++
    RUN cargo build --target armv7-unknown-linux-gnueabihf --release
    SAVE ARTIFACT target/armv7-unknown-linux-gnueabihf AS LOCAL target/armv7-unknown-linux-gnueabihf

build-linux-x86:
    FROM +project-files
    RUN cargo build --target x86_64-unknown-linux-gnu --release
    SAVE ARTIFACT target/x86_64-unknown-linux-gnu AS LOCAL target/x86_64-unknown-linux-gnu

build-windows-x86:
    FROM +project-files
    RUN apt update && apt upgrade -y
    RUN apt install -y g++-mingw-w64-x86-64
    RUN rustup target add x86_64-pc-windows-gnu
    RUN rustup toolchain install stable-x86_64-pc-windows-gnu
    RUN cargo build --target x86_64-pc-windows-gnu --release
    SAVE ARTIFACT target/x86_64-pc-windows-gnu AS LOCAL target/x86_64-pc-windows-gnu

build-macos-x86:
    FROM +project-files-macos
    RUN cargo build --target x86_64-apple-darwin --release
    SAVE ARTIFACT target/x86_64-apple-darwin AS LOCAL target/x86_64-apple-darwin