/******************************************************************************
 * # License
 * <b>Copyright 2021 Silicon Laboratories Inc. www.silabs.com</b>
 ******************************************************************************
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 *****************************************************************************/

/**
 * @file zcl_util_int.hpp
 * @defgroup zcl_util_int Internal API used within the ZCL utility component.
 * @ingroup zcl_util
 *
 * @{
 */

#ifndef ZIGPC_ZCL_UTIL_INT_HPP
#define ZIGPC_ZCL_UTIL_INT_HPP

#include "zcl_definitions.h"

/**
 * @brief Get the autogenerated ZCL data type to size map
 *
 * @return const std::unordered_map<zigpc_zcl_data_type_t, size_t>*
 */
const std::unordered_map<zigpc_zcl_data_type_t, size_t> *zigpc_zcl_get_zcl_data_type_size_map(void);

#endif /* ZIGPC_ZCL_UTIL_INT_HPP */

/** @} end zcl_util_int */
